#!/bin/bash

#PBS -N FLUENT
#PBS -j oe
#PBS -m e
#PBS -M ai0013@mix.wvu.edu
#PBS -l nodes=1:ppn=40
#PBS -V
#PBS -q vyakkerman


module load ansys/fluids_19.2

cd $PBS_O_WORKDIR
nprocs=`wc -l $PBS_NODEFILE | awk '{ print $1 }'`

fluent -gu 3d -ssh -cnf=$PBS_NODEFILE -mpi=ibmmpi -t40 -i /gpfs20/scratch/ai0013/gideon/ParticleStudy_Axelbaum/inputload_wvel.in


;For view HELP menu start fluent as: fluent -h
;Running a non-interactive job won't allow you to check the TUI display, 



